//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTour
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> ThanhToan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Tour Tour1 { get; set; }
    }
}
