//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID { get; set; }
        public string SoTaiKhoan { get; set; }
        public string TenChuTaiKhoan { get; set; }
        public Nullable<int> NganHangID { get; set; }
        public Nullable<decimal> Tien { get; set; }
    
        public virtual TaiKhoan TaiKhoan1 { get; set; }
        public virtual TaiKhoan TaiKhoan2 { get; set; }
    }
}
